from .common import Mission, Step, World, fresh, lines_of

WORLD = World(0, "Hello, Herdr", missions=[
    Mission("0.1", "Just a terminal", xp=30, par=30, steps=[
        Step("The big box is a real shell. Type **echo hello** and press Enter.",
             setup=fresh,
             goal=lambda c: c.s.pane and any(l.strip() == "hello" for l in lines_of(c.read(c.s.fpane))),
             hints=["Click in the big box if needed, type echo hello, then press Enter."],
             done="See? A pane is just a terminal. Herdr adds structure around it."),
    ]),
    Mission("0.2", "The prefix", xp=40, par=30, card="prefix", steps=[
        Step("Press the prefix: hold Ctrl, tap b, let go. (`ctrl+b`) Watch the bottom-right corner.",
             goal=lambda c: c.did("prefix"),
             hints=["Hold the Ctrl key, press b once, then release both.", "`ctrl+b`"],
             keys=["prefix"], demo=["prefix"],
             done="See the PREFIX bar? Herdr is waiting for one action key."),
        Step("Changed your mind? Press `esc` to cancel prefix mode.",
             goal=lambda c: c.pressed("cancel"),
             hints=["The Escape key, top-left of your keyboard.", "`ctrl+b` then `esc`"],
             done="Prefix, then one key. That's the whole trick."),
    ]),
    Mission("0.3", "The panic button", xp=40, par=40, steps=[
        Step("Open the list of every key: `prefix+?`  (ctrl+b, let go, then ?)",
             goal=lambda c: c.pressed("help"),
             hints=["? is Shift+/ on most keyboards.", "`ctrl+b` then `?`"],
             keys=["help"], demo=["prefix+?"],
             done="Every key Herdr knows, grouped by what it does."),
        Step("Search it: press `/`, then type **zoom**.",
             goal=lambda c: "/" in c.mode_keys("help") and "z" in c.mode_keys("help"),
             mistakes=[(lambda c: c.tracker_mode() == "terminal", "The keybinds panel closed. Open it again: `prefix+?`")],
             hints=["With the keybinds panel open, press / then type zoom.", "`/` z o o m"],
             done="Filtering finds any key in a second."),
        Step("Close it with `esc` (press it twice: once clears the search, once closes).",
             goal=lambda c: c.tracker_mode() == "terminal",
             hints=["Escape, then Escape again."],
             done="Forgot a key? `prefix+?` then `/`. That's your panic button."),
    ]),
    Mission("0.4", "Point and click", xp=40, par=40, card="mouse", steps=[
        Step("Herdr is mouse-first. **Click** the `+` in the tab bar at the top, then press Enter.",
             goal=lambda c: c.did("new-tab"),
             hints=["Look at the very top row: after the tab names there's a +. Click it.",
                    "Click +, then press Enter to accept the suggested name. (`prefix+c` does it too.)"],
             keys=["mouse"],
             done="A new tab! (You'll learn the keys for tabs in World 3.)"),
        Step("Now **click** the first tab, `1`, to go back to it.",
             goal=lambda c: c.s.ws and c.s.ws.tabs and c.s.ftab == c.s.ws.tabs[0].id,
             hints=["The tab bar is the top row. Click the 1."],
             done="Clicking works for panes, tabs, workspaces and agents. Keys are just faster."),
    ]),
])
